setup: relax -Werror for declaration-after-statement on Python 3.9
It turns out Python 3.9 introduces such declarations in the headers, eg

cpython/abstract.h:189:5: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]

so we have to be more relaxed when compiling for 3.9.

Differential Revision: https://phab.mercurial-scm.org/D8327