error: add `hint` attribute to `SidedataHashError`
This prevents an exception within an exception because `hint` does not exist.

Differential Revision: https://phab.mercurial-scm.org/D10024