doc: use an absolute path in sys.path to work around a python DLL loading bug
This bug[1] was causing the zstd entry under "Available Compression Engines" to
be omitted from the documentation for some versions of python3.  I could
upgrade, but past upgrades have broken venvs and clobbered installed packages.
It's a trivial workaround, so there's no sense in leaving this subtle issue.  It
was flushed out by changing the module policy here from 'allow' to 'c', and
seeing this error:

    ImportError: DLL load failed while importing parsers: The parameter is incorrect.

[1] https://github.com/python/cpython/issues/87271

Differential Revision: https://phab.mercurial-scm.org/D12599