cborutil: fix streamencode() to handle subtypes
Otherwise the template filter 'cbor' could crash because of bytes subclass:

  ValueError: do not know how to encode
  <class 'mercurial.encoding.safelocalstr'>